services:
  knrbcheck:
    build: .
    container_name: knrbcheck
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true
