services:
  knrbcheck:
    build: .
    container_name: knrbcheck
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./stats.json:/app/stats.json
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true
